server:
  port: 8082
  servlet:
    context-path: / # ?????????????

spring:
  profiles:
    active: dev # ???????? dev ????????????? application-dev.yml

  application:
    name: orange-tools-backend

  # Jackson ??????? (?????????8?????????????)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # ?????? (????????????????)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis-Plus ???? (????)
mybatis-plus:
  type-aliases-package: cn.orangetools.**.entity # ?????????
  global-config:
    banner: false # ?????? MyBatis-Plus ??????????
    db-config:
      id-type: auto # ???????????? (???? assign_id ????)